rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2

env:
  - MONGOID_VERSION=2
  - MONGOID_VERSION=3
  - MONGOID_VERSION=4

matrix:
  exclude:
    - rvm: 1.9.2
      env: MONGOID_VERSION=3
    - rvm: 1.9.2
      env: MONGOID_VERSION=4

services:
  - mongodb